### ISSUE TITLE
reduce amount of unchecked code in converted benchmarks

### ISSUE THREAD

**Issue by dtarditi** [Microsoft/checkedc-llvm-test-suite#42]
As part of a paper submission, we counted the lines of code that were unchecked scopes.  There are some converted benchmarks where we could reduce the amount of code in unchecked scopes:
- Olden/TreeAdd: node.c
- Olden/Power: main.c
In addition, memset had a bounds-safe annotation that included an unchecked pointer type, which forced all memset calls to be unchecked code.  This should be correct as well.
There may be other converted benchmarks where the amount of unchecked code could be reduced.

One question is what is the criteria for putting code in a checked scope or unchecked scope.  Here is what I propose initially:
- It is fine to put print calls that use varargs in unchecked scopes by themselves.
- Function bodies or blocks that are > 80% checked code (excluding print calls) should be checked.

**Comment by lenary** [comment]
I'm going to try to get the low hanging fruit in treeadd node.c and power main.c, if any other places need this treatment i'd be happy to hear it.

**Comment by lenary** [comment]
Completed in #54
