### ISSUE TITLE
Copy modified headers back to Checked C repo

### ISSUE THREAD

**Issue by dtarditi** [Microsoft/checkedc-llvm-test-suite#43]
We find issues while converting existing benchmarks to be Checked C, mostly having to do with supporting specific platform's C standard library headers.  We updated the headers in this repo.  The changes to need to be propagated to the home repo of the headers, which is the Checked C repo.

**Comment by lenary** [comment]
I knew this issue existed somewhere! I couldn't find it when I searched the repos before.

I think #44 is a better solution to this issue, it will mean more pull-requests when we have to "fix" the checked headers, but I think in the long term it's a more sustainable approach.

**Comment by lenary** [comment]
Completed in quite a few pull requests, we've deleted the headers from this repo, removed the `include` dir from the include path, and now our fork of clang installs the checkedc headers automatically when it's built
