### ISSUE TITLE
CheckedC convert Ptrdist/ks benchmark

### ISSUE THREAD

**Issue by wonsubkim** [Microsoft/checkedc-llvm-test-suite#7]
convert Ptrdist/ks benchmark into checked-c code

- KS (Kernighan-Schweikert graph partitioning) benchmark is converted to checked-c
- anagram/ft is slightly modified to follow check-clang modification
- checkedc-llvm-test-suite checked header files are modified to follow changes of checkedc header files

MultiSource/Benchmakr/Ptrdist all benchmarks are passed with lnt runtest

**Comment by lenary** [comment]
Closed by #8
