### ISSUE TITLE
CheckedC convert Olden/power benchmark

### ISSUE THREAD

**Issue by wonsubkim** [Microsoft/checkedc-llvm-test-suite#9]
power benchmark checkedc conversion issue
 - checked array type array subscript requires dynamic_check
   - Almost reasoning facts of program can remove away redundant dynamic_check
   - Also static analysis such as constant folding can remove away dynamic_check
 - checked pointer dereference
   - a->b == (*a).b, it means pointer dereference and requires non-null runtime check

**Comment by lenary** [comment]
Closed by #10
